- name: apt install nginx
  become: true
  apt:
    name: nginx
    state: present

- name: deploy default nginx sites_enabled config
  become: true
  template:
    src: etc_nginx_sites_enabled_default.conf
    dest: /etc/nginx/sites-enabled/default
    mode: "0644"
    owner: root
    group: root

- name: deploy reverse proxy config for lobby
  become: true
  notify: reload_lobby_nginx
  template:
    src: etc_nginx_sites_enabled_lobby.conf
    dest: /etc/nginx/sites-enabled/lobby.conf
    mode: "0644"
    owner: root
    group: root

- name: ensure nginx is started
  become: true
  systemd:
    name: nginx
    state: started
    enabled: true

- name: allow firewall ports
  become: true
  ufw:
    rule: allow
    port: 443
    proto: tcp

