- name: create lobby user
  become: true
  user:
    name: "lobby"
    groups: "lobby,docker"
    create_home: no
    system: yes

- name: deploy systemctl service file to run lobby
  become: true
  template:
    src: lobby.service
    dest: /etc/systemd/system/lobby-2.6.service
    owner: root
    group: "{{ admin_group }}"
    mode: 0644

- name: deploy 'blue' lobby file
  become: true
  template:
    src: lobby-blue.service
    dest: /etc/systemd/system/lobby-blue.service
    owner: root
    group: "{{ admin_group }}"
    mode: 0644

- name: pull latest lobby
  become: true
  shell: |
    docker pull ghcr.io/triplea-game/lobby/server:latest

- name: ensure lobby blue is running
  become: true
  service:
    name: lobby-blue
    state: started
    enabled: false

- name: Wait some time for startup
  pause:
    seconds: 30

- name: switch nginx to the blue deployment
  become: true
  template:
    src: etc_nginx_sites_enabled_lobby.conf
    dest: /etc/nginx/sites-enabled/lobby.conf
    mode: "0644"
    owner: root
    group: root
  vars:
    proxy_port: "{{ lobby_blue_port }}"

- name: reload nginx
  become: true
  systemd:
    name: nginx
    state: reloaded
    enabled: true

- name: restart 2.6 lobby
  become: true
  service:
    name: lobby-2.6
    state: restarted
    enabled: true

- name: Wait some time for startup
  pause:
    seconds: 30

- name: switch nginx back to the updated green environment
  become: true
  template:
    src: etc_nginx_sites_enabled_lobby.conf
    dest: /etc/nginx/sites-enabled/lobby.conf
    mode: "0644"
    owner: root
    group: root
  vars:
    proxy_port: "{{ lobby_port }}"

- name: reload nginx
  become: true
  systemd:
    name: nginx
    state: reloaded
    enabled: true

- name: stop lobby blue
  become: true
  service:
    name: lobby-blue
    state: stopped
    enabled: true
