- name: Install postfix
  apt:
    state: present
    name: postfix

- name: Deploy postfix config
  template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: "0644"
  register: postfix_config

- name: Restart postfix if config changes
  when: postfix_config.changed
  systemd:
    name: postfix
    state: restarted

- name: Ensure postfix is started
  systemd:
    name: postfix
    state: started
