- name: check required variables
  assert:
    that:
      - database_name != ""
      - database_user != ""
      - database_password != ""

- name: Create postgres user account for the new database
  become_user: postgres
  postgresql_user:
    name: "{{ database_user }}"
    password: "{{ database_password }}"
    encrypted: yes
    state: "present"
    role_attr_flags: NOSUPERUSER,NOCREATEDB

- name: Create new database
  become_user: postgres
  postgresql_db:
    name: "{{ database_name }}"
    owner: "{{ database_user }}"

- name: Grant application user access to database
  become_user: postgres
  postgresql_privs:
    database: "{{ database_name }}"
    state: present
    privs: ALL
    type: database
    roles: "{{ database_user }}"
    grant_option: no
