- name: assert vars are set
  assert:
    that:
      - migrations_file != ""
      - flyway_db_name != ""
      - flyway_migration_dir != ""
      - flyway_user != ""
      - flyway_password != ""

- name: create migration folders
  file:
    state: directory
    mode: "0755"
    owner: flyway
    group: flyway
    path : "{{ flyway_migrations_location }}"

- name: extract migrations
  unarchive:
    src: "migrations.zip"
    dest: "{{ flyway_migrations_location }}"
    mode: "0644"
    owner: flyway
    group: flyway

- name: deploy file flyway.conf
  template:
    src: flyway.conf.j2
    dest: "{{ flyway_migrations_location }}/flyway.conf"
    mode: "0644"
    owner: flyway
    group: flyway

- name: run flyway
  command: |
      /opt/flyway/flyway-7.5.4/flyway
         -X
         -locations=filesystem:{{ flyway_migrations_location }}/{{ flyway_migration_dir }}
         -configFiles={{ flyway_migrations_location }}/flyway.conf
         migrate
  register: flyway
  changed_when: '"is up to date. No migration necessary" not in flyway.stdout'
  failed_when: >
    (flyway.rc != 0) or
    ("Successfully validated 0 migrations" in flyway.stdout) or
    ("WARNING: No migrations found. Are your locations set up correctly?" in flyway.stdout)
