- name: create service user to run flyway
  user:
    name: flyway
    create_home: no
    system: yes

- name: Create folder /opt/flyway/[version]/
  file:
    state: directory
    path: "{{ flyway_extracted_location }}"
    mode: "0755"
    owner: flyway
    group: flyway

- name: Download flyway CLI
  get_url:
    url: "{{ flyway_download_location }}"
    dest: "/opt/flyway/flyway-cli.tar.gz"
    mode: "0644"
    checksum: "md5:f5f2683e41cf2581693aad28f69fb4af"
    owner: flyway
    group: flyway

- name: extract flyway CLI
  unarchive:
    copy: no
    src: "/opt/flyway/flyway-cli.tar.gz"
    dest: "{{ flyway_extracted_location }}"
    owner: flyway
    group: flyway
    creates: "{{ flyway_extracted_location }}/flyway-{{ flyway_version }}"
