- name: run logrotate hourly instead of daily
  become: true
  command:
    cmd: mv /etc/cron.daily/logrotate /etc/cron.hourly/logrotate
    creates: /etc/cron.hourly/logrotate

- name: deploy config file /etc/logrotate.d/rsyslog
  become: true
  template:
    src: logrotate.d_rsyslog
    dest: /etc/logrotate.d/rsyslog
    owner: root
    group: root
    mode: "0644"

