# Runs when main branch is updated.
# Runs builds checks, if all passes then packages the lobby and redeploys

name: Main Branch Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
      - name: Run Build Checks
        # We skip 'spotlessApply' such that only 'spotlessCheck' will run to validate formatting.
        # This is a good setup for a CI server, meanwhile if a developer runs 'verify', they
        # will have the 'spotlessApply' task run to automatically format the code.
        run: make check
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Package application
        if: ${{ env.IS_MAIN_BUILD }}
        run: ./gradlew quarkusBuild
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: docker for optional database migrations with example seed data
        run: |
          docker build database/sample_data --tag ghcr.io/triplea-game/lobby/sample_data:latest
          docker push ghcr.io/triplea-game/lobby/sample_data:latest
      - name: docker for the java lobby server
        run: |
          docker build . --tag ghcr.io/triplea-game/lobby/server:latest
          docker push ghcr.io/triplea-game/lobby/server:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Load SSH private key into ssh-agent
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: "3.12"
      - name: Cache Ansible Galaxy collections
        uses: actions/cache@v4
        with:
          path: ~/.ansible/collections
          key: ansible-collections-${{ hashFiles('deploy/ansible/requirements.yml') }}
      - name: Install Ansible and dependencies
        run: |
          uv tool install --with linode_api4 --with-executables-from ansible-core,ansible-lint ansible
          ansible-galaxy collection install -r deploy/ansible/requirements.yml
      - name: Deploy
        env:
          LINODE_ACCESS_TOKEN: ${{ secrets.LINODE_READ_ONLY_TOKEN }}
        run: SSH_USER=deploy make deploy
