# Runs all build checks on any pull request or merges to master
name: Verify Pull Request
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Run Build Checks
        # We skip 'spotlessApply' such that only 'spotlessCheck' will run to validate formatting.
        # This is a good setup for a CI server, meanwhile if a developer runs 'verify', they
        # will have the 'spotlessApply' task run and it will automatically format the code.
        run: ./verify.sh --exclude-task spotlessApply
